name: EmeraldsCore
version: ${project.version}
api-version: "1.20"
description: EmeraldsCore Plugin
author: TSR
main: com.steve_rizzo.emeraldscore.Main
depend: [Vault]
soft-depend: [PlaceholderAPI, DiscordSRV]
commands:
  rank:
    description: Set a user's rank.
  fly:
    description: Set a user's ability to fly.
  flyspeed:
    description: Set user flight speed.
  spawn:
    description: Go to the world's spawn-point.
  bc:
    description: Broadcast a message to the server.
  broadcast:
    description: Broadcast a message to the server.
  gm:
    description: Sets the Game Mode of a player.
  eg:
    description: Receive a EmeraldsGames Navigator.
  farmworld:
    description: Go to FarmWorld!
    aliases: [ fw ]
  floorparty:
    description: Floor party!
  floatitem:
    description: Float an item from your hand!
  store:
    description: Displays a link to the server store!
  launchdonordrop:
    description: JACKPOT Drop Party!
  rules:
    description: Displays the server rules.
  afk:
    description: Toggle AFK status.
  staffchat:
    aliases: [ staff, sc ]
    description: Sends a message thru staffs chat.
  maintenance:
    aliases: [ maintenancemode, mm, maint ]
    description: Puts the server into maintenance mode.
  tokens:
    aliases: [ tokens, emeraldstokens ]
    description: Displays your tokens balance.
  settokens:
    description: Sets the Tokens of a player.
  givetokens:
    description: Gives Tokens to a player.
  tokenstop:
    description: Lists the top token balances of players on the server.
    aliases: [ ttop , tokentop ]
  balance:
    description: Displays your balance.
    aliases: [ bal , eco ]
  pay:
    aliases: [ sendmoney ]
    description: Send a player an amount of Emeralds Cash.
  setbalance:
    aliases: [ setbal ]
    description: Sets the balance of a player.
  takebalance:
    aliases: [ takebal ]
    description: Takes from the balance of a player.
  givebalance:
    aliases: [ givebal ]
    description: Gives to a balance of a player.
  baltop:
    aliases: [ balancetop, topbal, moneytop ]
    description: Lists the top balances of players on the server.
  apply:
    aliases: [ member ]
    description: Apply to become a member!
  rankshop:
    description: Opens the Emeralds Rank Shop.
  tokenshop:
    description: Opens the Emeralds Token Shop.
  message:
    description: Message another player.
    aliases: [ msg, whisper, pm ]
  reply:
    description: Reply to a message.
    aliases: [ r ]
  payheal:
    description: Pay for a heal!
    aliases: [ pheal ]
  survival:
    description: Travel to the Survival world!
    aliases: [ mainworld ]
  list:
    description: List online players.
    aliases: [ online ]
  help:
    description: Review helpful tools on EmeraldsMC.
  test:
    description: Launch a test
  villagersaver:
    description: Access villager saver commands.
  clearchat:
    description: Clears the chat.
    aliases: [ cc ]
  commands:
    description: List available server commands.
    aliases: [ cmds ]
  plugins:
    description: Show available plugins.
    aliases: [ pl ]
  boost:
    description: BOOST yourself into the air!
  claimfurnaces:
    description: Claim nearby smelted furnace items!
    aliases: [ cfurnaces ]
  buytokens:
    description: Purchase tokens using Emeralds Cash!
    aliases: [ buytoken, tokenbuy ]
  fireworks:
    description: Turn on/off the fireworks at spawn.
  back:
    description: Teleport to your death location.
  issueplot:
    description: Attempt to issue a market plot to a user.
  cat:
    description: Spawns the user a pet cat.
  dog:
    description: Spawns the user a pet dog.
  applybedwarstokens:
    description: Applies Bed Wars tokens to a user based on award type.
    aliases: [ apbt ]
  accept:
    description: Accepts a player's application and promotes them to member rank
    aliases: [ promote ]
  blackjack:
    description: Start a blackjack game.
  roulette:
    description: Start a roulette game.
  hit:
    description: Hit in blackjack.
  stand:
    description: Stand in blackjack.
  collect:
    description: Collect your rank income.