package com.steve_rizzo.emeraldscore.casino;

import com.steve_rizzo.emeraldscore.Main;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * /weblink <code>
 *
 * Verifies the 6-character code generated by the eCasino website,
 * linking the player's UUID to their web session so only they can
 * spend their EmeraldsCash balance through the site.
 */
public class WebLinkCommand implements CommandExecutor {

    private static final String SELECT_CODE =
            "SELECT id FROM WebLinks WHERE code = ? AND verified = 0";
    private static final String UPDATE_CODE =
            "UPDATE WebLinks SET uuid = ?, name = ?, verified = 1 WHERE code = ? AND verified = 0";

    /**
     * Creates the WebLinks table if it does not already exist.
     * Called once from Main.onEnable() after the HikariCP pool is ready.
     */
    public static void createTable() {
        try (Connection conn = Main.getInstance().getHikari();
             PreparedStatement ps = conn.prepareStatement(
                     "CREATE TABLE IF NOT EXISTS WebLinks (" +
                     "  id            INT AUTO_INCREMENT PRIMARY KEY," +
                     "  session_token VARCHAR(64) NOT NULL UNIQUE," +
                     "  code          VARCHAR(8)  NOT NULL UNIQUE," +
                     "  uuid          VARCHAR(36)," +
                     "  name          VARCHAR(16)," +
                     "  verified      TINYINT(1)  NOT NULL DEFAULT 0," +
                     "  created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP," +
                     "  INDEX idx_code  (code)," +
                     "  INDEX idx_token (session_token)" +
                     ")")) {
            ps.execute();
            System.out.println("[EmeraldsMC - WebLink]: WebLinks table ready.");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!(sender instanceof Player player)) {
            sender.sendMessage(ChatColor.RED + "Only players can use this command.");
            return true;
        }

        if (args.length != 1) {
            player.sendMessage(Main.prefix + ChatColor.YELLOW + "Usage: /weblink <code>");
            player.sendMessage(Main.prefix + ChatColor.GRAY + "Get your code at the eCasino website.");
            return true;
        }

        String code = args[0].toUpperCase();

        // Basic format check — 6 alphanumeric characters
        if (!code.matches("[A-Z0-9]{4,8}")) {
            player.sendMessage(Main.prefix + ChatColor.RED + "Invalid code format. Codes are 6 characters (e.g. AB3X7K).");
            return true;
        }

        try (Connection conn = Main.getInstance().getHikari();
             PreparedStatement select = conn.prepareStatement(SELECT_CODE)) {

            select.setString(1, code);
            ResultSet rs = select.executeQuery();

            if (!rs.next()) {
                player.sendMessage(Main.prefix + ChatColor.RED + "Code not found or already used. Generate a new one on the eCasino site.");
                return true;
            }

            try (PreparedStatement update = conn.prepareStatement(UPDATE_CODE)) {
                update.setString(1, player.getUniqueId().toString());
                update.setString(2, player.getName());
                update.setString(3, code);
                int rows = update.executeUpdate();

                if (rows == 0) {
                    player.sendMessage(Main.prefix + ChatColor.RED + "Code already used — please generate a fresh one.");
                    return true;
                }
            }

            player.sendMessage(Main.prefix + ChatColor.GREEN + "Success! Your Minecraft account is now linked to eCasino.");
            player.sendMessage(Main.prefix + ChatColor.GRAY + "Return to the website — it will log you in automatically.");

        } catch (SQLException e) {
            e.printStackTrace();
            player.sendMessage(Main.prefix + ChatColor.RED + "A database error occurred. Please try again.");
        }

        return true;
    }
}
